apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thomaseneh/Azure-CICD-Pipeline.git
    targetRevision: HEAD
    path: k8s-services
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNameSpace=true

    automated:
      selfHeal: true
      prune: true
